import { bytes,rate,escapeHtml as esc,type Snapshot } from './model';
import {usageColor} from './usage';

const meter=(value:number,color='var(--accent)')=>`<div class="resource-meter"><span style="width:${Math.max(0,Math.min(100,value))}%;background:${color}"></span></div>`;
export function renderPerformance(s:Snapshot):string {
 const p=s.performance;
 if(!p)return '<p class="muted">パフォーマンス情報を取得しています…</p>';
 return `<div class="resource-heading"><div><div class="eyebrow">HARDWARE / LIVE</div><h2>${esc(s.cpuName)}</h2></div><span class="resource-total">${s.sample.cpu.toFixed(0)}<small>% CPU</small></span></div>
 <section class="panel resource-section"><div class="section-title">論理プロセッサ <span class="count">${p.cpus.length}</span></div><div class="core-grid">${p.cpus.map((c,k)=>`<div class="core-tile" style="--resource-color:${usageColor(c.usage,'cpu')}"><span>CPU ${k}</span><strong>${c.usage.toFixed(0)}<small>%</small></strong>${meter(c.usage,usageColor(c.usage,'cpu'))}<span>${c.frequency?(c.frequency/1000).toFixed(2)+' GHz':'周波数 取得不可'}</span></div>`).join('')}</div></section>
 <div class="resource-columns"><section class="panel resource-section"><div class="section-title">物理メモリ</div><div class="resource-total" style="color:${usageColor(s.sample.memory,'memory')}">${bytes(s.usedMemory)}<small> / ${bytes(s.totalMemory)}</small></div>${meter(s.sample.memory,usageColor(s.sample.memory,'memory'))}<p class="muted">利用可能 ${bytes(s.totalMemory-s.usedMemory)}</p></section><section class="panel resource-section"><div class="section-title">スワップ / ページファイル</div><div class="resource-total">${bytes(p.usedSwap)}<small> / ${bytes(p.totalSwap)}</small></div>${meter(p.totalSwap?p.usedSwap/p.totalSwap*100:0)}<p class="muted">OSが報告するスワップ使用量</p></section></div>
 <div class="resource-columns">${p.disks.map(d=>`<section class="panel resource-section"><div class="section-title">${esc(d.mount)} <span class="count">${esc(d.kind)}</span></div><p class="muted">${esc(d.name)} · ${esc(d.filesystem)}</p><div class="resource-total">${bytes(d.total-d.available)}<small> / ${bytes(d.total)}</small></div>${meter(d.total?(d.total-d.available)/d.total*100:0)}<div class="resource-rates"><span>読み取り <strong>${rate(d.read)}</strong></span><span>書き込み <strong>${rate(d.write)}</strong></span></div><p class="muted">空き容量 ${bytes(d.available)}</p></section>`).join('')}</div>
 <section class="panel resource-section"><div class="section-title">GPU · LIVE</div><p class="muted">この画面を表示中のみ自動更新します。</p>${!p.gpu?'<p class="muted">GPUカウンターを準備しています…</p>':p.gpu.error?`<p role="status">${esc(p.gpu.error)}</p>`:p.gpu.adapters.map(g=>`<div class="resource-heading"><div><h2>${esc(g.name)}</h2><p class="muted">${esc(g.id)}</p></div><div class="resource-total">${p.gpu?.warming?'…':g.usage===null?'—':g.usage.toFixed(1)}<small>%</small></div></div>${meter(g.usage??0)}<div class="resource-rates"><span>専用メモリ <strong>${g.dedicatedUsed===null?'取得不可':bytes(g.dedicatedUsed)} / ${bytes(g.dedicatedTotal)}</strong></span><span>共有メモリ <strong>${g.sharedUsed===null?'取得不可':bytes(g.sharedUsed)} / ${bytes(g.sharedTotal)}</strong></span></div>`).join('')||'<p class="muted">GPUアダプターがありません</p>'}</section><section class="panel resource-section"><div class="section-title">ネットワークアダプター</div><div class="resource-networks">${p.interfaces.map(n=>`<div class="interface-row"><div><strong>${esc(n.name)}</strong><span class="muted">${esc(n.mac)}</span></div><div>↓ ${rate(n.download)}<span class="muted">累計 ${bytes(n.totalReceived)}</span></div><div>↑ ${rate(n.upload)}<span class="muted">累計 ${bytes(n.totalTransmitted)}</span></div></div>`).join('')||'<p class="muted">アダプターが見つかりません</p>'}</div></section>`;
}

export function previewPerformance():NonNullable<Snapshot['performance']> {
 return {gpu:{adapters:[{id:'DEMO GPU',name:'Demo Graphics',usage:18,dedicatedUsed:1.2*1073741824,sharedUsed:256*1048576,dedicatedTotal:8*1073741824,sharedTotal:16*1073741824}],error:null,warming:false},cpus:Array.from({length:20},(_,k)=>({name:`CPU ${k}`,usage:12+(k*17)%55,frequency:2600})),totalSwap:8*1073741824,usedSwap:1.2*1073741824,
 disks:[{name:'NVMe SSD',mount:'C:\\',kind:'SSD',filesystem:'NTFS',total:1024*1073741824,available:620*1073741824,read:4.2*1048576,write:1.3*1048576}],
 interfaces:[{name:'Wi-Fi',mac:'00:00:00:00:00:00',download:84*1024,upload:44*1024,totalReceived:23*1048576,totalTransmitted:8*1048576}]};
}
